# Describes the format for available Number entity services
# Currently reload service does not work (https://github.com/home-assistant/core/pull/93538).
#reload:
#  name: Reload
#  description: Reload all slow_pwm entities.

set_value:
  name: Set
  description: Set the value of a Number entity.
  target:
    entity:
      domain: number
  fields:
    value:
      name: Value
      description: The target value the entity should be set to.
      example: 42
      selector:
        text:
