# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.slow_pwm: debug

switch:
  - platform: template
    switches:
      dummy_1:
        turn_on:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 1 On
        turn_off:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 1 Off
      dummy_2:
        turn_on:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 2 On
        turn_off:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 2 Off
      dummy_3:
        turn_on:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 3 On
        turn_off:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 3 Off
      dummy_4:
        turn_on:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 4 On
        turn_off:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 4 Off
      dummy_5:
        turn_on:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 5 On
        turn_off:
          - service: logbook.log
            data:
              name: DebugOutput
              message: Dummy Switch 5 Off

number:
  - platform: slow_pwm
    name: Floorheater living room
    outputs:
      - "switch.dummy_5"
    minimum: 10
    maximum: 200
    cycle_time:  {'hours':0, 'minutes':20, 'seconds': 00}
    minimal_switch_time: {'hours':0, 'minutes':0, 'seconds': 30}
    step: 3
    mode: "auto"
    unique_id: "MyUniqueID_1234"